services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"

  web:
    build: .
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: ["/entrypoint.sh"]
    command: ["/usr/bin/xsp4", "--port=8080", "--nonstop"]
    ports:
      - "8090:8080"
    depends_on:
      - db
