# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookly-web
  namespace: bookly
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bookly-web
  template:
    metadata:
      labels:
        app: bookly-web
    spec:
      containers:
        - name: bookly-web
          image: bojananaumovska/bookly-mono:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookly-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bookly-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookly-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookly-secret
                  key: DB_PASSWORD
